### ISSUE TITLE
scale_fixes Notes

### ISSUE THREAD

**Issue by corellmichael** [Qu-Bit-Electronix/QB_Nebulae_V2#21]
# Notes

## Bowed Drone

- Does not seem to output any sound

## Drip Water

- Reverb Mix does not seem to work

## Four Osc (I think it's only 3 oscillators if I'm not mistaken)

- update the pdf file to match controls
	- Fix oscillator knobs (Start: Master, Density: Osc 1, Size: Osc 2, Overlap: Osc 3)
	- add slew (blend) knob and VCA (window) knob that aren't labeled
	- Speed and Pitch don't do anything, not sure if they are suppose to 

## Plucked Patterns

- Attack/Release do not work

**Comment by albsciu** [comment]
Hi, is there anyone working on these issues?
